spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${JDBC_DATABASE_URL:"jdbc:mysql://localhost:3306/fuel_logg?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:}
#For uploading photos with url!
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  #  sql:
  #    init:
  #      mode: always
  jpa:
# Choose either MySQL 8 or MySQL 5 below

# For MySQL 8
#    database-platform: org.hibernate.dialect.MySQL8Dialect

#For MySQL 5
#database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

# For Postgre dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  main:
    allow-bean-definition-overriding: true
server:
  error:
    path: /error
  port: ${PORT:8080}


#Cloudinary Properties
cloudinary:
  api-key: 493324265438926
  api-secret:  ${CLOUDINARY_API_SECRET}
  cloud-name: dogm4cmbj

